### Método para recupera todos los platos
GET http://localhost:5000/dishes

### Método para recuperar un plato por ID
GET http://localhost:5000/dishes/6863322acc2416032bce5557

### Método para traerte todos los patos de una categoría
GET http://localhost:5000/dishes?category=Entrantes

### Método para crear un plato nuevo
POST http://localhost:5000/dishes
Content-Type: application/json

{
  "name": "plato de prueba",
  "description": "descripcion de prueba",
  "ingredients": [
    "ingrediente 1",
    "ingrediente 2"
  ],
  "allergens": ["alergenos de prueba"],
  "image": "url etcetcetc",
  "price_ars": 10000,
  "price_usd": 5,
  "categories": [
    "categoria 1",
    "categoria 2",
    "categoria 3"
  ]
}

### Método para actualizar parcialemnte un plato existente
PATCH http://localhost:5000/dishes/68633dd37a3c60aa9a20f414
Content-Type: application/json

{
  "name": "Bruschetta Clásica",
  "allergens": [
    "Gluten"
  ]
}

### Método para borrar un plato mediante su ID
DELETE http://localhost:5000/dishes/68634ae1673542552756009b