export const db = [
  {
    "id": 1,
    "name": "Bruschetta Clásica",
    "description": "Rebanadas de pan tostado con tomate fresco, albahaca y aceite de oliva.",
    "ingredients": ["Pan", "Tomate", "Albahaca", "Aceite de oliva", "Ajo"],
    "allergens": ["Gluten"],
    "image": "/dishImages/Entradas/bruschettas.png",
    "price_ars": 1500,
    "price_usd": 1.50,
    "categories": ["Entrantes"]
  },
  {
    "id": 2,
    "name": "Empanadas de Carne",
    "description": "Empanadas tradicionales argentinas rellenas de carne picada y especias.",
    "ingredients": ["Harina", "Carne de res", "Cebolla", "Pimiento", "Especias"],
    "allergens": ["Gluten"],
    "image": "/dishImages/Entradas/empanada.png",
    "price_ars": 1800,
    "price_usd": 1.80,
    "categories": ["Entrantes"]
  },
  {
    "id": 3,
    "name": "Empanadas de Jamón y Queso",
    "description": "Empanadas tradicionales argentinas rellenas de jamón y queso.",
    "ingredients": ["Harina", "Jamón", "Queso", "Especias"],
    "allergens": ["Gluten"],
    "image": "/dishImages/Entradas/empanada.png",
    "price_ars": 1800,
    "price_usd": 1.80,
    "categories": ["Entrantes"]
  },
  {
    "id": 4,
    "name": "Empanadas de Humita",
    "description": "Empanadas tradicionales argentinas de rellenas de Choclo, Crema y Cebolla.",
    "ingredients": ["Harina", "Choclo", "Crema", "Cebolla", "Especias"],
    "allergens": ["Gluten"],
    "image": "/dishImages/Entradas/empanada.png",
    "price_ars": 1800,
    "price_usd": 1.80,
    "categories": ["Entrantes"]
  },
  {
    "id": 5,
    "name": "Provoleta",
    "description": "Queso provolone fundido con orégano y aceite de oliva.",
    "ingredients": ["Queso provolone", "Orégano", "Aceite de oliva"],
    "allergens": ["Lácteos"],
    "image": "/dishImages/Entradas/provoleta.png",
    "price_ars": 2000,
    "price_usd": 2.00,
    "categories": ["Entrantes"]
  },
  {
    "id": 6,
    "name": "Tabla de Fiambres",
    "description": "Selección de fiambres y quesos artesanales.",
    "ingredients": ["Jamón", "Salame", "Quesos variados", "Aceitunas"],
    "allergens": ["Lácteos"],
    "image": "/dishImages/Entradas/tabla-picada.png",
    "price_ars": 2500,
    "price_usd": 2.50,
    "categories": ["Entrantes"]
  },
  {
    "id": 7,
    "name": "Ensalada César",
    "description": "Lechuga romana con aderezo César, crutones y queso parmesano.",
    "ingredients": ["Lechuga romana", "Aderezo César", "Crutones", "Queso parmesano"],
    "allergens": ["Lácteos", "Gluten", "Huevos"],
    "image": "/dishImages/Ensaladas/ensalada-boconccino.png",
    "price_ars": 1700,
    "price_usd": 1.70,
    "categories": ["Ensaladas"]
  },
  {
    "id": 8,
    "name": "Ensalada de Quinoa",
    "description": "Quinoa con vegetales asados y vinagreta de limón.",
    "ingredients": ["Quinoa", "Zanahoria", "Pimiento", "Zucchini", "Limón"],
    "allergens": [],
    "image": "/dishImages/Ensaladas/ensalada-quinoa.png",
    "price_ars": 1800,
    "price_usd": 1.80,
    "categories": ["Ensaladas"]
  },
  {
    "id": 9,
    "name": "Ensalada Mediterránea",
    "description": "Mezcla de hojas verdes, aceitunas, pepino y queso feta.",
    "ingredients": ["Lechuga", "Espinaca", "Aceitunas", "Pepino", "Queso feta"],
    "allergens": ["Lácteos"],
    "image": "/dishImages/Ensaladas/ensalada-mediterranea.png",
    "price_ars": 1900,
    "price_usd": 1.90,
    "categories": ["Ensaladas"]
  },
  {
    "id": 10,
    "name": "Ensalada Burrata",
    "description": "Mezcla de hojas verdes, tomate cherry y queso Burrata.",
    "ingredients": ["Albahaca", "Tomate", "Queso Burrata"],
    "allergens": ["Lácteos"],
    "image": "/dishImages/Ensaladas/ensalada-burrata.png",
    "price_ars": 1900,
    "price_usd": 1.90,
    "categories": ["Ensaladas"]
  },
  {
    "id": 11,
    "name": "Ensalada Bocconcino",
    "description": "Mezcla de hojas verdes, tomate cherry y queso Bocconcino.",
    "ingredients": ["Albahaca", "Tomate", "Queso Bocconcino"],
    "allergens": ["Lácteos"],
    "image": "/dishImages/Ensaladas/ensalada-boconccino.png",
    "price_ars": 1900,
    "price_usd": 1.90,
    "categories": ["Ensaladas"]
  },
  {
    "id": 12,
    "name": "Bife de Chorizo",
    "description": "El clásico corte argentino a la parrilla, jugoso por dentro.",
    "ingredients": ["Bife de chorizo"],
    "allergens": [],
    "image": "/dishImages/carnes-rojas/bife-chorizo.png",
    "price_ars": 4000,
    "price_usd": 4.00,
    "categories": ["Platos Principales - Carnes Rojas"]
  },
  {
    "id": 13,
    "name": "Bife de Lomo",
    "description": "El corte más tierno de la res a la parrilla.",
    "ingredients": ["Bife de lomo"],
    "allergens": [],
    "image": "/dishImages/carnes-rojas/bife-lomo.png",
    "price_ars": 5000,
    "price_usd": 5.00,
    "categories": ["Platos Principales - Carnes Rojas"]
  },
  {
    "id": 14,
    "name": "Milanesa de Carne Napolitana",
    "description": "Milanesa de ternera empanada, cubierta con salsa de tomate, jamón y queso fundido.",
    "ingredients": ["Ternera", "Pan rallado", "Huevo", "Salsa de tomate", "Jamón", "Queso mozzarella"],
    "allergens": ["Gluten", "Huevos", "Lácteos"],
    "image": "/dishImages/carnes-rojas/milanesa-napolitana.png",
    "price_ars": 3000,
    "price_usd": 3.00,
    "categories": ["Platos Principales - Carnes Rojas"]
  },
  {
    "id": 15,
    "name": "Suprema Napolitana",
    "description": "Pechuga de pollo empanada, cubierta con salsa de tomate, jamón y queso mozzarella.",
    "ingredients": ["Pollo", "Pan rallado", "Salsa de tomate", "Jamón", "Queso mozzarella"],
    "allergens": ["Gluten", "Lácteos"],
    "image": "/dishImages/carnes-blancas/milanesa-pollo-napolitana.png",
    "price_ars": 2400,
    "price_usd": 2.40,
    "categories": ["Platos Principales - Carnes Blancas"]
  },
  {
    "id": 16,
    "name": "Pollo al Curry",
    "description": "Trozos de pollo cocinados en una cremosa salsa de curry, servidos con arroz blanco.",
    "ingredients": ["Pollo", "Curry", "Crema", "Arroz", "Cebolla"],
    "allergens": ["Lácteos"],
    "image": "/dishImages/carnes-blancas/pollo-curry.png",
    "price_ars": 2300,
    "price_usd": 2.30,
    "categories": ["Platos Principales - Carnes Blancas"]
  },
  {
    "id": 17,
    "name": "Pollo a la Cacciatore",
    "description": "Pollo guisado con tomates, cebolla, pimientos y hierbas aromáticas.",
    "ingredients": ["Pollo", "Tomate", "Cebolla", "Pimientos", "Hierbas"],
    "allergens": [],
    "image": "/dishImages/carnes-blancas/pollo-cacciatore.png",
    "price_ars": 2250,
    "price_usd": 2.25,
    "categories": ["Platos Principales - Carnes Blancas"]
  },
  {
    "id": 18,
    "name": "Pollo al Limón",
    "description": "Pechuga de pollo a la plancha con salsa de limón y acompañamiento de vegetales.",
    "ingredients": ["Pollo", "Limón", "Vegetales", "Aceite de oliva"],
    "allergens": [],
    "image": "/dishImages/carnes-blancas/pollo-al-limon.png",
    "price_ars": 2150,
    "price_usd": 2.15,
    "categories": ["Platos Principales - Carnes Blancas"]
  },
  {
    "id": 19,
    "name": "Pollo Teriyaki",
    "description": "Trozos de pollo salteados en salsa teriyaki, servidos con arroz y semillas de sésamo.",
    "ingredients": ["Pollo", "Salsa teriyaki", "Arroz", "Sésamo"],
    "allergens": ["Soja", "Sésamo"],
    "image": "/dishImages/carnes-blancas/pollo-teriyaki.png",
    "price_ars": 2350,
    "price_usd": 2.35,
    "categories": ["Platos Principales - Carnes Blancas"]
  },
  {
    "id": 20,
    "name": "Salmón a la Plancha",
    "description": "Filete de salmón a la plancha con salsa de eneldo y puré de papas.",
    "ingredients": ["Salmón", "Eneldo", "Papas", "Manteca"],
    "allergens": ["Pescado", "Lácteos"],
    "image": "/dishImages/pescados/salmon.png",
    "price_ars": 2600,
    "price_usd": 2.60,
    "categories": ["Platos Principales - Pescado"]
  },
  {
    "id": 21,
    "name": "Merluza al Horno",
    "description": "Filete de merluza al horno con limón y hierbas, acompañado de vegetales al vapor.",
    "ingredients": ["Merluza", "Limón", "Hierbas", "Vegetales"],
    "allergens": ["Pescado"],
    "image": "/dishImages/pescados/filet-merluza-napolitana.png",
    "price_ars": 2400,
    "price_usd": 2.40,
    "categories": ["Platos Principales - Pescado"]
  },
  {
    "id": 22,
    "name": "Paella de Mariscos",
    "description": "Arroz cocinado con una variedad de mariscos y azafrán.",
    "ingredients": ["Arroz", "Camarones", "Mejillones", "Calamares", "Azafrán"],
    "allergens": ["Mariscos"],
    "image": "/dishImages/pescados/paella-mariscos.png",
    "price_ars": 2800,
    "price_usd": 2.80,
    "categories": ["Platos Principales - Pescado"]
  },
  {
    "id": 23,
    "name": "Capeletti",
    "description": "Pasta rellena, típicamente servida con salsa a elección.",
    "ingredients": ["Pasta", "Relleno (carne o verdura)"],
    "allergens": ["Gluten", "Huevos"],
    "image": "/dishImages/Pastas/cappeleti.png",
    "price_ars": 2500,
    "price_usd": 2.50,
    "categories": ["Pastas"]
  },
  {
    "id": 24,
    "name": "Ñoquis",
    "description": "Clásicos ñoquis de papa caseros, servidos con salsa a elección.",
    "ingredients": ["Papa", "Harina", "Huevo"],
    "allergens": ["Gluten", "Huevos"],
    "image": "/dishImages/Pastas/ñoquis.png",
    "price_ars": 2300,
    "price_usd": 2.30,
    "categories": ["Pastas"]
  },
  {
    "id": 25,
    "name": "Penne Rigatti",
    "description": "Pasta corta rayada, ideal para acompañar con salsas con cuerpo.",
    "ingredients": ["Pasta"],
    "allergens": ["Gluten"],
    "image": "/dishImages/Pastas/penne-rigatti.png",
    "price_ars": 2200,
    "price_usd": 2.20,
    "categories": ["Pastas"]
  },
  {
    "id": 26,
    "name": "Spaghetti",
    "description": "Clásico spaghetti, perfecto con una variedad de salsas.",
    "ingredients": ["Pasta"],
    "allergens": ["Gluten"],
    "image": "/dishImages/Pastas/spaghetti.png",
    "price_ars": 2200,
    "price_usd": 2.20,
    "categories": ["Pastas"]
  },
  {
    "id": 27,
    "name": "Sorrentinos",
    "description": "Pasta redonda grande rellena, servida con salsa a elección.",
    "ingredients": ["Pasta", "Relleno (jamón y queso o calabaza)"],
    "allergens": ["Gluten", "Huevos", "Lácteos"],
    "image": "/dishImages/Pastas/sorrentinos.png",
    "price_ars": 2600,
    "price_usd": 2.60,
    "categories": ["Pastas"]
  },
  {
    "id": 28,
    "name": "Tiramisú",
    "description": "Clásico postre italiano a base de bizcochos savoiardi, café, crema de mascarpone y cacao.",
    "ingredients": ["Vainillas", "Café", "Mascarpone", "Huevos", "Azúcar", "Cacao"],
    "allergens": ["Gluten", "Lácteos", "Huevos"],
    "image": "/dishImages/Postre/tiramisu.jpg",
    "price_ars": 2200,
    "price_usd": 2.20,
    "categories": ["Postres"]
  },
  {
    "id": 29,
    "name": "Volcán de Chocolate",
    "description": "Bizcocho tibio de chocolate con un corazón líquido, acompañado de helado de crema.",
    "ingredients": ["Chocolate", "Manteca", "Huevos", "Azúcar", "Harina", "Helado de crema"],
    "allergens": ["Lácteos", "Huevos", "Gluten"],
    "image": "/dishImages/Postre/volcan.jpg",
    "price_ars": 2400,
    "price_usd": 2.40,
    "categories": ["Postres"]
  },
  {
    "id": 30,
    "name": "Flan con Dulce de Leche y Crema",
    "description": "Flan casero tradicional, acompañado de abundante dulce de leche y crema batida.",
    "ingredients": ["Huevos", "Leche", "Azúcar", "Dulce de leche", "Crema"],
    "allergens": ["Huevos", "Lácteos"],
    "image": "/dishImages/Postre/flan.jpg",
    "price_ars": 2000,
    "price_usd": 2.00,
    "categories": ["Postres"]
  },
  {
    "id": 31,
    "name": "Agua sin Gas",
    "description": "Botella de agua mineral sin gas.",
    "ingredients": ["Agua"],
    "allergens": [],
    "image": "/dishImages/bebidas-sin-alcohol/agua-sin-gas.png",
    "price_ars": 800,
    "price_usd": 0.80,
    "categories": ["Bebidas sin Alcohol"]
  },
  {
    "id": 32,
    "name": "Agua con Gas",
    "description": "Botella de agua mineral con gas.",
    "ingredients": ["Agua carbonatada"],
    "allergens": [],
    "image": "/dishImages/bebidas-sin-alcohol/agua-con-gas.png",
    "price_ars": 800,
    "price_usd": 0.80,
    "categories": ["Bebidas sin Alcohol"]
  },
  {
    "id": 33,
    "name": "Aquarius de Pomelo",
    "description": "Bebida saborizada Aquarius sabor pomelo.",
    "ingredients": ["Agua", "Azúcar", "Jugo de pomelo", "Acidulante", "Saborizantes"],
    "allergens": [],
    "image": "/dishImages/bebidas-sin-alcohol/pomelo.png",
    "price_ars": 900,
    "price_usd": 0.90,
    "categories": ["Bebidas sin Alcohol"]
  },
  {
    "id": 34,
    "name": "Aquarius de Manzana",
    "description": "Bebida saborizada Aquarius sabor manzana.",
    "ingredients": ["Agua", "Azúcar", "Jugo de manzana", "Acidulante", "Saborizantes"],
    "allergens": [],
    "image": "/dishImages/bebidas-sin-alcohol/manzana.png",
    "price_ars": 900,
    "price_usd": 0.90,
    "categories": ["Bebidas sin Alcohol"]
  },
  {
    "id": 35,
    "name": "Coca-Cola",
    "description": "Gaseosa Coca-Cola sabor original.",
    "ingredients": ["Agua carbonatada", "Azúcar", "Colorante", "Acidulante", "Saborizantes", "Cafeína"],
    "allergens": [],
    "image": "/dishImages/bebidas-sin-alcohol/coca.png",
    "price_ars": 1000,
    "price_usd": 1.00,
    "categories": ["Bebidas sin Alcohol"]
  },
  {
    "id": 36,
    "name": "Coca-Cola Zero",
    "description": "Gaseosa Coca-Cola sin azúcar.",
    "ingredients": ["Agua carbonatada", "Colorante", "Acidulante", "Saborizantes", "Edulcorantes", "Cafeína"],
    "allergens": [],
    "image": "/dishImages/bebidas-sin-alcohol/coca-zero.png",
    "price_ars": 1000,
    "price_usd": 1.00,
    "categories": ["Bebidas sin Alcohol"]
  },
  {
    "id": 37,
    "name": "Vino Tinto D.O.C. Malbec Luigi Bosca",
    "description": "Vino tinto Malbec con Denominación de Origen Controlada Luján de Cuyo.",
    "ingredients": ["Uva Malbec"],
    "allergens": ["Sulfitos"],
    "image": "/dishImages/bebidas-con-alcohol/vino-tinto-malbec.png",
    "price_ars": 12000,
    "price_usd": 12.00,
    "categories": ["Bebidas con Alcohol"]
  },
  {
    "id": 38,
    "name": "Vino Tinto Red Blend Luigi Bosca",
    "description": "Vino tinto blend de uvas tintas seleccionadas de Bodega Luigi Bosca.",
    "ingredients": ["Uvas tintas seleccionadas"],
    "allergens": ["Sulfitos"],
    "image": "/dishImages/bebidas-con-alcohol/red-blend.png",
    "price_ars": 10000,
    "price_usd": 10.00,
    "categories": ["Bebidas con Alcohol"]
  },
  {
    "id": 39,
    "name": "Vino Tinto Malbec de Sangre Luigi Bosca",
    "description": "Vino tinto Malbec de alta gama de la línea De Sangre de Luigi Bosca.",
    "ingredients": ["Uva Malbec"],
    "allergens": ["Sulfitos"],
    "image": "/dishImages/bebidas-con-alcohol/vino-tinto-malbec.png",
    "price_ars": 14000,
    "price_usd": 14.00,
    "categories": ["Bebidas con Alcohol"]
  },
  {
    "id": 40,
    "name": "Vino Tinto Cabernet Sauvignon Luigi Bosca",
    "description": "Vino tinto varietal Cabernet Sauvignon de Bodega Luigi Bosca.",
    "ingredients": ["Uva Cabernet Sauvignon"],
    "allergens": ["Sulfitos"],
    "image": "/dishImages/bebidas-con-alcohol/cabernet-sauvignon.png",
    "price_ars": 10000,
    "price_usd": 10.00,
    "categories": ["Bebidas con Alcohol"]
  },
  {
    "id": 41,
    "name": "Vino Blanco Chardonnay Luigi Bosca",
    "description": "Vino blanco varietal Chardonnay de Bodega Luigi Bosca.",
    "ingredients": ["Uva Chardonnay"],
    "allergens": ["Sulfitos"],
    "image": "/dishImages/bebidas-con-alcohol/vino-blanco-chardonnay.png",
    "price_ars": 9000,
    "price_usd": 9.00,
    "categories": ["Bebidas con Alcohol"]
  },
  {
    "id": 42,
    "name": "Vino Tinto Malbec Luigi Bosca",
    "description": "Vino tinto varietal Malbec de Bodega Luigi Bosca.",
    "ingredients": ["Uva Malbec"],
    "allergens": ["Sulfitos"],
    "image": "/dishImages/bebidas-con-alcohol/vino-tinto-malbec-luigi.png",
    "price_ars": 9500,
    "price_usd": 9.50,
    "categories": ["Bebidas con Alcohol"]
  }
]
